# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aleksei_Varaksin_Online_Shop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aleksei_Varaksin_Online_Shop
  pod 'Alamofire', '~> 4.9.1'

  target 'Aleksei_Varaksin_Online_ShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Aleksei_Varaksin_Online_ShopUITests' do
    # Pods for testing
  end

end
